openapi: 3.0.1
info:
  title: BRS-API
  version: 1.0.0
servers:
  - url: /
security:
  - default: []
paths:
  '/entity/get_attachment_list/{no}/{Key}':
    get:
      parameters:
        - name: 'no'
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: string
        - name: Key
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: string
      responses:
        '200':
          description: ok
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        security-types:
          - oauth2
        optional: false
components:
  securitySchemes:
    default:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: ''
          scopes: {}
x-wso2-auth-header: Authorization
x-wso2-cors:
  corsConfigurationEnabled: false
  accessControlAllowOrigins:
    - '*'
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
    - authorization
    - Access-Control-Allow-Origin
    - Content-Type
    - SOAPAction
    - apikey
    - testKey
  accessControlAllowMethods:
    - GET
    - PUT
    - POST
    - DELETE
    - PATCH
    - OPTIONS
x-wso2-production-endpoints:
  urls:
    - 'https://apitest.ursb.go.ug/test00/api/'
  type: http
x-wso2-sandbox-endpoints:
  urls:
    - 'https://apitest.ursb.go.ug/test00/api/'
  type: http
x-wso2-basePath: /brs
x-wso2-transports:
  - http
  - https
x-wso2-response-cache:
  enabled: false
  cacheTimeoutInSeconds: 300
