components:
  securitySchemes:
    default:
      flows:
        implicit:
          authorizationUrl: ""
          scopes: {}
      type: oauth2
info:
  title: BRS-API
  version: 1.0.0
openapi: 3.0.1
paths:
  /classifier/get_classifier/{domain}/{institution}:
    get:
      parameters:
      - explode: false
        in: path
        name: domain
        required: true
        schema:
          format: string
          type: string
        style: simple
      - explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /classifier/get_classifier_list/{institution}:
    get:
      parameters:
      - explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /entity/get_attachment/{registration_no}/{attachment_id}/{institution}:
    get:
      description: Download specific attachment
      parameters:
      - description: Entity registration number
        explode: false
        in: path
        name: registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Attachment ID
        explode: false
        in: path
        name: attachment_id
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /entity/get_attachment_list/{registration_no}/{institution}:
    get:
      description: Get list of all available attachments for a specific entity
      parameters:
      - description: Entity registration number
        explode: false
        in: path
        name: registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /entity/get_entity_full/{registration_no}/{old_registration_no}/{institution}:
    get:
      description: Get full data set for a specific entity
      parameters:
      - description: Entity registration number
        explode: false
        in: path
        name: registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Previous entity registration number
        explode: false
        in: path
        name: old_registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /entity/get_entity_list/{from}/{to}/{institution}:
    get:
      description: Get list of the entities for the specified time period
      parameters:
      - description: Period start date of entity registration/incorporation
        explode: false
        in: path
        name: from
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Period end date of entity registration/incorporation
        explode: false
        in: path
        name: to
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /entity/get_entity_minimum/{registration_no}/{old_registration_no}/{institution}:
    get:
      description: Get minimum data set for a specific entity
      parameters:
      - description: Entity registration number
        explode: false
        in: path
        name: registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: Previous entity registration number
        explode: false
        in: path
        name: old_registration_no
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
  /search/get_name_similarity/{entity_name}/{institution}:
    get:
      description: Get list of similar names for the specified name
      parameters:
      - description: Entity name you are searching for
        explode: false
        in: path
        name: entity_name
        required: true
        schema:
          format: string
          type: string
        style: simple
      - description: External institution Unique ID issued by BRS
        explode: false
        in: path
        name: institution
        required: true
        schema:
          format: string
          type: string
        style: simple
      responses:
        "200":
          description: ok
      security:
      - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-wso2-application-security:
        optional: false
        security-types:
        - oauth2
security:
- default: []
servers:
- url: /
x-wso2-auth-header: Authorization
x-wso2-basePath: /brs-api/1.0.0
x-wso2-cors:
  accessControlAllowCredentials: false
  accessControlAllowHeaders:
  - authorization
  - Access-Control-Allow-Origin
  - Content-Type
  - SOAPAction
  - apikey
  - testKey
  accessControlAllowMethods:
  - GET
  - PUT
  - POST
  - DELETE
  - PATCH
  - OPTIONS
  accessControlAllowOrigins:
  - '*'
  corsConfigurationEnabled: false
x-wso2-production-endpoints:
  type: http
  urls:
  - https://apitest.ursb.go.ug/test00/api/
x-wso2-response-cache:
  cacheTimeoutInSeconds: 300
  enabled: false
x-wso2-sandbox-endpoints:
  type: http
  urls:
  - https://apitest.ursb.go.ug/test00/api/
x-wso2-transports:
- http
- https
